language: python
python:
  - "3.8"

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable

before_script:
  - pipenv install
  - install-webdrivers --path webdrivers

branches:
  only:
    - dev

env: DJANGO_SETTINGS_MODULE="off_project.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test
