language: python
python:
  - "3.8"

before_script:
  - pipenv install

branches:
  only:
    - dev

env: DJANGO_SETTINGS_MODULE="off_project.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test
